/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Database.DBConnect;
import controller.registerController;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author fahmi
 */
public class registerPage extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public registerPage() {
        initComponents();
        registerController control = new registerController(this);
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        CustomerRegisterPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        RegisterCustomerUsernameField = new javax.swing.JTextField();
        RegisterCustomerNamaField = new javax.swing.JTextField();
        RegisterCustomerPasswordField = new javax.swing.JPasswordField();
        RegisterCustomerTeleponField = new javax.swing.JTextField();
        RegisterCustomerAlamatField = new javax.swing.JTextField();
        RegisterCustomerButton = new javax.swing.JButton();
        jButton2backlogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("REGISTER");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(503, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Jika belum punya akun, Silahkan Registrasi terlebih dahulu");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        CustomerRegisterPanel.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Username");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Nama");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Password");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("No telepon");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Alamat");

        RegisterCustomerUsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterCustomerUsernameFieldActionPerformed(evt);
            }
        });

        RegisterCustomerNamaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterCustomerNamaFieldActionPerformed(evt);
            }
        });

        RegisterCustomerPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterCustomerPasswordFieldActionPerformed(evt);
            }
        });

        RegisterCustomerTeleponField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterCustomerTeleponFieldActionPerformed(evt);
            }
        });

        RegisterCustomerAlamatField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterCustomerAlamatFieldActionPerformed(evt);
            }
        });

        RegisterCustomerButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        RegisterCustomerButton.setText("Register");
        RegisterCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterCustomerButtonregisterActionPerformed(evt);
            }
        });

        jButton2backlogin.setText("Back to Login");
        jButton2backlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2backloginbackloginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CustomerRegisterPanelLayout = new javax.swing.GroupLayout(CustomerRegisterPanel);
        CustomerRegisterPanel.setLayout(CustomerRegisterPanelLayout);
        CustomerRegisterPanelLayout.setHorizontalGroup(
            CustomerRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerRegisterPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(CustomerRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2backlogin)
                    .addGroup(CustomerRegisterPanelLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(CustomerRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(38, 38, 38)
                        .addGroup(CustomerRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(RegisterCustomerTeleponField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(RegisterCustomerPasswordField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RegisterCustomerNamaField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RegisterCustomerButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RegisterCustomerUsernameField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RegisterCustomerAlamatField))))
                .addContainerGap(256, Short.MAX_VALUE))
        );
        CustomerRegisterPanelLayout.setVerticalGroup(
            CustomerRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustomerRegisterPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(CustomerRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RegisterCustomerUsernameField)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CustomerRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RegisterCustomerNamaField)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CustomerRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RegisterCustomerPasswordField)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CustomerRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RegisterCustomerTeleponField)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CustomerRegisterPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RegisterCustomerAlamatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CustomerRegisterPanelLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4)))
                .addGap(34, 34, 34)
                .addComponent(RegisterCustomerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 99, Short.MAX_VALUE)
                .addComponent(jButton2backlogin)
                .addContainerGap())
        );

        getContentPane().add(CustomerRegisterPanel, java.awt.BorderLayout.PAGE_END);
        CustomerRegisterPanel.getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterCustomerButtonregisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterCustomerButtonregisterActionPerformed
        String uname = RegisterCustomerUsernameField.getText();
        String name = RegisterCustomerNamaField.getText();
        String pass = String.valueOf(RegisterCustomerPasswordField.getPassword());
        String telp = RegisterCustomerTeleponField.getText();
        String adres = RegisterCustomerAlamatField.getText();

        PreparedStatement ps;
        String query = "INSERT INTO `sqlcustomer`(`username`, `nama`, `password`, `no_telp`, `alamat`) VALUES (?,?,?,?,?)";
        try {
            ps = (PreparedStatement) DBConnect.getConnection().prepareStatement(query);
            ps.setString(1, uname);
            ps.setString(2, name);
            ps.setString(3, pass);
            ps.setString(4, telp);
            ps.setString(5, adres);

            if (ps.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(null, "New user add");
            }
        } catch (SQLException ex) {
            Logger.getLogger(registerPage.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_RegisterCustomerButtonregisterActionPerformed

    private void RegisterCustomerPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterCustomerPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterCustomerPasswordFieldActionPerformed

    private void RegisterCustomerUsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterCustomerUsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterCustomerUsernameFieldActionPerformed

    private void RegisterCustomerNamaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterCustomerNamaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterCustomerNamaFieldActionPerformed

    private void RegisterCustomerTeleponFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterCustomerTeleponFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterCustomerTeleponFieldActionPerformed

    private void RegisterCustomerAlamatFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterCustomerAlamatFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterCustomerAlamatFieldActionPerformed

    private void jButton2backloginbackloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2backloginbackloginActionPerformed
        this.dispose();
        loginPage obj = new loginPage();
        obj.setVisible(true);
        obj.setLocationRelativeTo(null);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2backloginbackloginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CustomerRegisterPanel;
    private javax.swing.JTextField RegisterCustomerAlamatField;
    private javax.swing.JButton RegisterCustomerButton;
    private javax.swing.JTextField RegisterCustomerNamaField;
    private javax.swing.JPasswordField RegisterCustomerPasswordField;
    private javax.swing.JTextField RegisterCustomerTeleponField;
    private javax.swing.JTextField RegisterCustomerUsernameField;
    private javax.swing.JButton jButton2backlogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
    
    
}
